contract('MultiAsset', function(accounts) {
  it('should not be possible to issue asset with existing symbol');
  it('should not be possible to issue asset with empty symbol');
  it('should be possible to issue asset with 1 character symbol');
  it('should be possible to issue asset with 32 characters symbol');
  it('should not be possible to issue asset with 33 characters symbol');
  it('should not be possible to issue fixed asset with 0 value');
  it('should be possible to issue fixed asset with 1 value');
  it('should be possible to issue fixed asset with 2**255 value');
  it('should not be possible to issue fixed asset with (2**255 + 1) value');
  it('should be possible to issue reissuable asset with 0 value');
  it('should be possible to issue reissuable asset with 1 value');
  it('should be possible to issue reissuable asset with 2**255 value');
  it('should not be possible to issue reissuable asset with (2**255 + 1) value');
  it('should not be possible to issue asset with base unit 0');
  it('should be possible to issue asset with base unit 1');
  it('should be possible to issue asset with base unit 128');
  it('should not be possible to issue asset with base unit 129');
  it('should be possible to issue asset');
  it('should be possible to get asset name');
  it('should be possible to get asset description');
  it('should be possible to get asset base unit');
  it('should be possible to get asset reissuability');
  it('should be possible to get asset total supply with single holder');
  it('should be possible to get asset total supply with multiple holders');
  it('should be possible to get asset total supply with multiple holders holding 0 amount');
  it('should be possible to get asset balance for holder');
  it('should be possible to get asset balance for missing holder');
  it('should be possible to get missing asset balance for holder');
  it('should be possible to get missing asset balance for missing holder');
  it('should not be possible to get name of missing asset');
  it('should not be possible to get description of missing asset');
  it('should not be possible to get base unit of missing asset');
  it('should not be possible to get reissuability of missing asset');
  it('should not be possible to get total supply of missing asset');
  it('should not be possible to transfer missing asset');
  it('should not be possible to transfer amount 1 with balance 0');
  it('should not be possible to transfer amount 2 with balance 1');
  it('should not be possible to transfer amount 2**255 with balance (2**255 - 1)');
  it('should not be possible to transfer amount 0');
  it('should not be possible to transfer amount 2**255 to holder with 1 balance');
  it('should not be possible to transfer amount 1 to holder with 2**255 balance');
  it('should not be possible to transfer amount 2**254 to holder with (2**254 + 1) balance');
  it('should not be possible to transfer amount (2**254 + 1) to holder with 2**254 balance');
  it('should be possible to transfer amount 2**254 to holder with 2**254 balance');
  it('should be possible to transfer amount (2**255 - 1) to holder with 1 balance');
  it('should be possible to transfer amount 1 to holder with (2**255 - 1) balance');
  it('should be possible to transfer amount 1 to existing holder with 0 balance');
  it('should be possible to transfer amount 1 to existing holder with non-zero balance');
  it('should be possible to transfer amount 2**255 to holder with 0 balance');
  it('should be possible to transfer amount 1 to existing holder with non-zero balance');
  it('should be possible to transfer amount 1 to missing holder');
  it('should be possible to transfer amount 2**255 to missing holder');
  it('should not be possible to reissue fixed asset');
  it('should not be possible to reissue 0 of reissuable asset');
  it('should not be possible to reissue missing asset');
  it('should not be possible to reissue 1 with total supply 2**255');
  it('should not be possible to reissue 2**255 with total supply 1');
  it('should be possible to reissue 1 with total supply (2**255 - 1)');
  it('should be possible to reissue 1 with total supply 0');
  it('should be possible to reissue 2**255 with total supply 0');
  it('should be possible to reissue (2**255 - 1) with total supply 1');
  it('should be possible to reissue 2**254 with total supply 2**254');
  it('should not be possible to revoke 1 from missing asset');
  it('should not be possible to revoke 0 from fixed asset');
  it('should not be possible to revoke 0 from reissuable asset');
  it('should not be possible to revoke 1 with balance 0');
  it('should not be possible to revoke 2 with balance 1');
  it('should not be possible to revoke 2**255 with balance (2**255 - 1)');
  it('should not be possible to revoke 2**254 with balance (2**254 - 1)');
  it('should be possible to revoke 1 from fixed asset with 1 balance');
  it('should be possible to revoke 1 from reissuable asset with 1 balance');
  it('should be possible to revoke 2**254 with 2**254 balance');
  it('should be possible to revoke 2**255 with 2**255 balance');
  it('should be possible to revoke 1 with 2 balance');
  it('should be possible to revoke 2 with 2**255 balance');
  it('should be possible to reissue 1 after revoke 1 with total supply 2**255');
  it('should not mess with other assets/holders');
});