contract MultiAssetInterface {
    function setupRegistryICAP(address _registryICAP) returns(bool);
    function setupEventsHistory(address _eventsHistory) returns(bool);
    function isCreated(bytes32 _symbol) constant returns(bool);
    function baseUnit(bytes32 _symbol) constant returns(uint8);
    function name(bytes32 _symbol) constant returns(string);
    function description(bytes32 _symbol) constant returns(string);
    function isReissuable(bytes32 _symbol) constant returns(bool);
    function owner(bytes32 _symbol) constant returns(address);
    function isOwner(address _owner, bytes32 _symbol) constant returns(bool);
    function totalSupply(bytes32 _symbol) constant returns(uint);
    function balanceOf(address _holder, bytes32 _symbol) constant returns(uint);
    function setProxy(address _address, bool enabled, bytes32 _symbol) returns(bool);
    function setEventsProxy(address _address, bytes32 _symbol) returns(bool);
    function setProxyConf(bool _onlyThroughProxy, bool _throwOnFailedEmit, bytes32 _symbol) returns(bool);
    function transfer(address _to, uint _value, bytes32 _symbol) returns(bool);
    function transferToICAP(bytes32 _icap, uint _value) returns(bool);
    function transferToICAPWithReference(bytes32 _icap, uint _value, string _reference) returns(bool);
    function transferWithReference(address _to, uint _value, bytes32 _symbol, string _reference) returns(bool);
    function proxyTransferWithReference(address _to, uint _value, bytes32 _symbol, string _reference) returns(bool);
    function proxyTransferToICAPWithReference(bytes32 _icap, uint _value, string _reference) returns(bool);
    function getHolderId(address _holder) constant returns(uint);
    function issueAsset(bytes32 _symbol, uint _value, string _name, string _description, uint8 _baseUnit, bool _isReissuable) returns(bool);
    function reissueAsset(bytes32 _symbol, uint _value) returns(bool);
    function revokeAsset(bytes32 _symbol, uint _value) returns(bool);
    function changeOwnership(bytes32 _symbol, address _newOwner) returns(bool);
    function isTrusted(address _from, address _to) constant returns(bool);
    function trust(address _to) returns(bool);
    function distrust(address _to) returns(bool);
    function distrustAll() returns(bool);
    function recover(address _from, address _to) returns(bool);
    function approve(address _spender, uint _value, bytes32 _symbol) returns(bool);
    function proxyApprove(address _spender, uint _value, bytes32 _symbol) returns(bool);
    function allowance(address _from, address _spender, bytes32 _symbol) constant returns(uint);
    function transferFrom(address _from, address _to, uint _value, bytes32 _symbol) returns(bool);
    function transferFromWithReference(address _from, address _to, uint _value, bytes32 _symbol, string _reference) returns(bool);
    function transferFromToICAP(address _from, bytes32 _icap, uint _value) returns(bool);
    function transferFromToICAPWithReference(address _from, bytes32 _icap, uint _value, string _reference) returns(bool);
    function proxyTransferFromWithReference(address _from, address _to, uint _value, bytes32 _symbol, string _reference) returns(bool);
    function proxyTransferFromToICAPWithReference(address _from, bytes32 _icap, uint _value, string _reference) returns(bool);
    function setCosignerAddress(address _address, bytes32 _symbol) returns(bool);
    function setCosignerAddressForUser(address _address) returns(bool);
    function proxySetCosignerAddress(address _address, bytes32 _symbol) returns(bool);
}